// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry            = require("bs-platform/lib/js/curry.js");
var ReactNative      = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact      = require("reason-react/lib/js/src/reasonReact.js");
var WeatherComponent = require("./WeatherComponent.js");

var component = ReasonReact.statelessComponent("App");

function make(weatherApiKey, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* None */0,
                      /* array */[ReasonReact.element(/* None */0, /* None */0, WeatherComponent.make(weatherApiKey, /* array */[]))]
                    ]));
    });
  return newrecord;
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.weatherApiKey, /* array */[]);
      }));

exports.component = component;
exports.make      = make;
exports.$$default = $$default;
exports.default   = $$default;
exports.__esModule= true;
/* component Not a pure module */
