// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry    = require("bs-platform/lib/js/curry.js");
var Option   = require("bs-batteries/lib/js/src/option.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var $great$great$eq = Option.Monad[/* bind */1];

var $$return = Option.Monad[/* return */0];

function equals(cmp, opt) {
  return Curry._2($great$great$eq, opt, (function (a) {
                return Curry._1($$return, Caml_obj.caml_equal(a, cmp));
              }));
}

var Option$1 = /* module */[
  /* >>= */$great$great$eq,
  /* return */$$return,
  /* equals */equals
];

function ste(prim) {
  return prim;
}

exports.Option = Option$1;
exports.ste    = ste;
/* No side effect */
