// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function ofKelvin(f) {
  return /* float array */[f];
}

function ofCelcius(f) {
  return /* float array */[f];
}

function ofFarenheit(f) {
  return /* float array */[f];
}

function kelvinToCelcius(param) {
  return /* float array */[param[/* temp */0] - 275.15];
}

function celciusToKelvin(param) {
  return /* float array */[param[/* temp */0] + 275.15];
}

function celciusToFarenheit(param) {
  return /* float array */[param[/* temp */0] * 9.0 / 5.0 + 32.0];
}

function farenheitToCelcius(param) {
  return /* float array */[(param[/* temp */0] - 32.0) * 5.0 / 9.0];
}

function kelvinToFarenheit(k) {
  return celciusToFarenheit(kelvinToCelcius(k));
}

function farenheitToKelvin(f) {
  return celciusToKelvin(farenheitToCelcius(f));
}

function toFloat(param) {
  return param[/* temp */0];
}

function degrees(w) {
  return w[/* temp */0].toFixed() + "\xb0";
}

function $plus(param, param$1) {
  return /* float array */[param[/* temp */0] + param$1[/* temp */0]];
}

function $neg(param, param$1) {
  return /* float array */[param[/* temp */0] - param$1[/* temp */0]];
}

exports.ofKelvin           = ofKelvin;
exports.ofCelcius          = ofCelcius;
exports.ofFarenheit        = ofFarenheit;
exports.kelvinToCelcius    = kelvinToCelcius;
exports.celciusToKelvin    = celciusToKelvin;
exports.celciusToFarenheit = celciusToFarenheit;
exports.farenheitToCelcius = farenheitToCelcius;
exports.kelvinToFarenheit  = kelvinToFarenheit;
exports.farenheitToKelvin  = farenheitToKelvin;
exports.toFloat            = toFloat;
exports.degrees            = degrees;
exports.$plus              = $plus;
exports.$neg               = $neg;
/* No side effect */
